version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: expensesense_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-expensesense_db}
      MYSQL_USER: ${DB_USER:-expenseuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-expensepass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - expensesense_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Django Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expensesense_backend
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 expensesense_backend.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    networks:
      - expensesense_network

volumes:
  mysql_data:
  static_volume:
  media_volume:

networks:
  expensesense_network:
    driver: bridge
