# Generated by Django 4.2.7 on 2025-10-27 16:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transportation'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('bills', 'Bills & Utilities'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('groceries', 'Groceries'), ('travel', 'Travel'), ('other', 'Other')], db_index=True, default='other', max_length=50)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateTimeField(db_index=True)),
                ('sms_raw_text', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='expenses_user_id_d1baf3_idx'), models.Index(fields=['user', 'category'], name='expenses_user_id_ed2a40_idx')],
            },
        ),
    ]
